### ISSUE TITLE
start visualization by visualizing IPL data ? 

### ISSUE THREAD

**Issue by maze-runnar** [Team-Tomato/Cricket-Data-analysis#1]
> start visualization by visualizing IPL data ?   

@tamilarasumk731 @Inbasasi @AkbarHabeeb any thoughts on this.

**Comment by AkbarHabeeb** [comment]
@maze-runnar Yes we can do it. For now, we are sticking to the International T20 data alone. Do u got any other idea?

**Comment by AkbarHabeeb** [comment]
Staled
